### ISSUE TITLE
Some ACKs fail

### ISSUE THREAD

**Issue by Alex-Kuz** [tarantool/sharded-queue#27]
Not all ACKs are performed at storages, which is why the completed (from the client’s point of view) task is subsequently deleted by TTL.
<img width="1225" alt="Screenshot 2020-05-20 at 14 40 33" src="https://user-images.githubusercontent.com/17350870/82539832-c43c4b80-9b56-11ea-8add-a4e667402e7e.png">
<img width="1244" alt="Screenshot 2020-05-20 at 14 40 11" src="https://user-images.githubusercontent.com/17350870/82539838-c7cfd280-9b56-11ea-9b65-8cb297514203.png">

UPD:
Some relevant information about the setup:
 - TTL is set to 1 hour (as well as TTR, by default)
 - Number of queue clients -- 8, from graphs it looks like acks are missing when the clients are underloaded.

**Comment by akudiyar** [comment]
After updating the installation to the version with fixes https://github.com/tarantool/sharded-queue/pull/17 and https://github.com/tarantool/sharded-queue/pull/19, the picture changed:
<img width="2949" alt="portal-service-detail-tarantool - Grafana 2020-05-26 11-59-38" src="https://user-images.githubusercontent.com/2381032/82887142-40b49d00-9f50-11ea-900b-c1ed4c60596f.png">

It can be interpreted as the lags on Cartridge storages have gone and we see constant missing acks (highly likely) due to the errors on the client (task consumer) side. Investigation of consumer logs is needed.

**Comment by Totktonada** [comment]
Jira: TNT-15.

**Comment by sharonovd** [comment]
xXx xXx, [16.02.21 15:32]
Привет. Мы наконец то перешли с легаси-перла на го и проблем с "залипаением" больше нет. Предварительно проблема в легаси-коннекторе

xXx xXx, [16.02.21 15:32]
т.е. sharded-queue работает как надо
